### ISSUE TITLE
Can't get quotes for new tokens unless restart jup api - `data: { error: 'No route found' }`

### ISSUE THREAD

**Issue by dancamarg0** [jup-ag/jupiter-swap-api#11]
One of our clients is reporting this error and we can reproduce that.

Here's a new token we could not query until we restarted the jupiter_swap_api for example:

```
quote?inputMint=So11111111111111111111111111111111111111112&outputMint=E4fVrxVL7xM19hqvp8U8VGJr6pCFdxNzvjCdrgngnQtH&amount=3000000000&slippageBps=0&asLegacyTransaction=false&maxAccounts=25&swapMode=ExactOut
```

**Comment by arrowcircle** [comment]
I have the same issue, any updates on this?

**Comment by dancamarg0** [comment]
It looks like this behavior is expected and the jupiter API doesn't have the ability to hot-reload markets yet.

What we do to work-around it is to deploy on systemd and set `RuntimeMaxSec=3600` to restart every hour
