### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: RPC response error -32601: Method not found 

### ISSUE THREAD

**Issue by paulalsop** [jup-ag/jupiter-swap-api#17]
:~$ RUST_BACKTRACE=full RUST_LOG=info ./jupiter-swap-api --rpc-url http://127.0.0.1:8899
[2024-04-04T04:41:42.258781Z INFO  jupiter_swap_api] Found 48 logical cores, using 48 for the api
[2024-04-04T04:41:42.261958Z WARN  jupiter_swap_api] Running in poll mode, this mode is not recommended
[2024-04-04T04:41:42.261988Z INFO  jupiter_swap_api] Loading Jupiter router...
[2024-04-04T04:41:45.675289Z INFO  jupiter_core::amms::loader] markets len(): 55365
thread 'main' panicked at jupiter-swap-api/src/main.rs:663:10:
called `Result::unwrap()` on an `Err` value: RPC response error -32601: Method not found 

Caused by:
    RPC response error -32601: Method not found 
stack backtrace:
   0:     0x55c178b34c2c - <unknown>
   1:     0x55c178b60610 - <unknown>
   2:     0x55c178b31caf - <unknown>
   3:     0x55c178b34a14 - <unknown>
   4:     0x55c178b363c7 - <unknown>
   5:     0x55c178b3612f - <unknown>
   6:     0x55c178b36848 - <unknown>
   7:     0x55c178b3672e - <unknown>
   8:     0x55c178b350f6 - <unknown>
   9:     0x55c178b36492 - <unknown>
  10:     0x55c178228115 - <unknown>
  11:     0x55c178228653 - <unknown>
  12:     0x55c1783476e4 - <unknown>
  13:     0x55c178299973 - <unknown>
Aborted (core dumped)
solv@ip-172-31-11-167:~$

**Comment by siong1987** [comment]
your RPC is throwing the error here.
