### ISSUE TITLE
ENABLE_ADD_MARKET usage

### ISSUE THREAD

**Issue by maa105** [jup-ag/jupiter-swap-api#23]
running `./jupiter/jupiter-swap-api --help`
gives:
```
Usage: jupiter-swap-api [OPTIONS] --rpc-url <RPC_URL> [ENABLE_ADD_MARKET]

Arguments:
  [ENABLE_ADD_MARKET]  Enable the /add-market endpoint to hot load a new market
```

I tried: `jupiter-swap-api --rpc-url <MY_RPC_URL> true`, `jupiter-swap-api --rpc-url <MY_RPC_URL> 1`, `jupiter-swap-api --rpc-url <MY_RPC_URL> ENABLE_ADD_MARKET` and `jupiter-swap-api --rpc-url <MY_RPC_URL> [ENABLE_ADD_MARKET]` all gave:

```
error: 0 values required for '[ENABLE_ADD_MARKET]' but 1 was provided
```

I think this is a bug with parsing cli argument. can you point me to the usage of `ENABLE_ADD_MARKET` please I cant find it in the documentation

**Comment by siong1987** [comment]
it has been updated on the latest release.
