### ISSUE TITLE
bug: custom destinationTokenAccount is not writable

### ISSUE THREAD

**Issue by josephinfinex** [jup-ag/jupiter-swap-api#25]
please refer to transaction https://solscan.io/tx/63P8GP1nD8TZeVeEYHPtK7znfLnpJAVsFBZvCD2y2Qgno3EuUaPgSujJjSPSTYLo4MhMvidCudY3KgKjrkc6SgPu

when the destinationTokenAccount is set, it got a `writable privilege escalated` error
<img width="755" alt="Screenshot 2024-05-27 at 3 54 08 pm" src="https://github.com/jup-ag/jupiter-swap-api/assets/168153099/8885a2f4-289f-421b-86a3-6b060b83a5ac">. 
as per screenshot, the accountmeta for the destination token account is incorrectly set as `readonly`

**Comment by siong1987** [comment]
should be fixed.

**Comment by creativekdev** [comment]
https://solscan.io/tx/37GAcwzCfEbydZknATZXRMjDEzMPKV5b3TF3VtM2JUD5y6cKoKWipQD5qfpB2MLtmkDsLgVhzyWrU5kdHRi9HRqh

I am trying to swap and send the swapped token to merchant address but it's failed.

how to fix this?
