### ISSUE TITLE
Failed to load jupiter strict tokens:

### ISSUE THREAD

**Issue by LinBBB** [jup-ag/jupiter-swap-api#29]
[2024-07-19T07:07:33.473633Z ERROR jupiter_core::slippage] Failed to load jupiter strict tokens: error sending request for url (https://token.jup.ag/strict): error trying to connect: dns error: Too many open files (os error 24)
thread 'main' panicked at jupiter-swap-api/src/main.rs:802:10:
called `Result::unwrap()` on an `Err` value: RPC request error: cluster version query failed: error sending request for url (http://127.0.0.1:8899/): error trying to connect: tcp open error: Too many open files (os error 24)

Caused by:
    RPC request error: cluster version query failed: error sending request for url (http://127.0.0.1:8899/): error trying to connect: tcp open error: Too many open files (os error 24)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    303457 IOT instruction (core dumped)  RUST_LOG=info ./jupiter-swap-api --rpc-url http://127.0.0.1:8899

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by siong1987** [comment]
this is your OS error.

**Comment by Quan3Xin** [comment]
You can change ulimt with your system
