### ISSUE TITLE
Permit same pair swaps

### ISSUE THREAD

**Issue by defliction** [jup-ag/jupiter-swap-api#6]
The API does not permit same pair swaps. 

`{"error":"Input and output mints are not allowed to be equal"}`

This should be enabled with cli flag depending on desired configuration of deployment.

**Comment by Godxia** [comment]
still "error":"Input and output mints are not allowed to be equal"

**Comment by siong1987** [comment]
it is permitted now with the `/swap` endpoint.

**Comment by SocialAnxty** [comment]
> it is permitted on self hosted.

How do you enable it? It is currently blocking me and im self hosted. I am getting the error:

400 Bad Request and error {"error":"Input and output mints are not allowed to be equal","errorCode":"CIRCULAR_ARBITRAGE_IS_DISABLED"}
